@startuml
'https://plantuml.com/object-diagram

object Lexer{
    Lexer
    TokenIterator
    TokenizeStrategy
}
object Interpreter{
    Evaluator
    Interpreter
    Scope
    Variable
}
object Runner{
    Runner
    ErrorHandler
    Event
    Observer
    Observable
}
object Parser{
    Parser
    ExpressionIterator
    ParseException
    Grammar
    InfixParser
    PrefixParser
}
object Token{
    Token
    TokenWriter
    TokenMapSuite
    TokenType
}
object AST{
    Expression
    ExpressionVisitor
}
object CLI{
    Analyze
    CLI
    CliErrorHandler
    CliInputProvider
    CliPrinter
    Execute
    Format
}
object Linter{
    Linter
    LinterResult
    LintingRule
    LinterRuleSetter
    LintingConfig
}
object Formatter{
    Formatter
    FormatterConfig
    FormatterTokenIterator
    }
object Lib{
    InputProvider
    Position
    PrintEmitter
}

Runner -down-> Interpreter
Runner -down-> Parser
Runner -down-> Linter
Runner -down-> Formatter
Runner -down-> Lexer
CLI -down-> Runner
Lexer -down-> Token
Parser -down-> Token
Formatter -down-> Token
Linter -down-> Token
Parser -down-> AST
Interpreter -down-> AST
Token -down-> Lib
AST -down-> Lib
Runner -down-> Lib
Interpreter -down-> Lib
Parser -down-> Lib
Lexer -down-> Lib
CLI -down-> Lib

@enduml